package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_agent_order_logtc", Class = BizAgentOrderLogtc.class)
public class BizAgentOrderLogtcCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public BizAgentOrderLogtcCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public BizAgentOrderLogtcCriteria(BizAgentOrderLogtcCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public BizAgentOrderLogtcCriteria(Object record, BizAgentOrderLogtcCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_agent_order_logtc
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andLogtcIdIsNull() {
            addCriterion("LOGTC_ID is null");
            return this;
        }

        public Criteria andLogtcIdIsNotNull() {
            addCriterion("LOGTC_ID is not null");
            return this;
        }

        public Criteria andLogtcIdEqualTo(String value) {
            addCriterion("LOGTC_ID =", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdNotEqualTo(String value) {
            addCriterion("LOGTC_ID <>", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdGreaterThan(String value) {
            addCriterion("LOGTC_ID >", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGTC_ID >=", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdLessThan(String value) {
            addCriterion("LOGTC_ID <", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdLessThanOrEqualTo(String value) {
            addCriterion("LOGTC_ID <=", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdLike(String value) {
            addCriterion("LOGTC_ID like", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdNotLike(String value) {
            addCriterion("LOGTC_ID not like", value, "logtcId");
            return this;
        }

        public Criteria andLogtcIdIn(List values) {
            addCriterion("LOGTC_ID in", values, "logtcId");
            return this;
        }

        public Criteria andLogtcIdNotIn(List values) {
            addCriterion("LOGTC_ID not in", values, "logtcId");
            return this;
        }

        public Criteria andLogtcIdBetween(String value1, String value2) {
            addCriterion("LOGTC_ID between", value1, value2, "logtcId");
            return this;
        }

        public Criteria andLogtcIdNotBetween(String value1, String value2) {
            addCriterion("LOGTC_ID not between", value1, value2, "logtcId");
            return this;
        }

        public Criteria andLogtcNameIsNull() {
            addCriterion("LOGTC_NAME is null");
            return this;
        }

        public Criteria andLogtcNameIsNotNull() {
            addCriterion("LOGTC_NAME is not null");
            return this;
        }

        public Criteria andLogtcNameEqualTo(String value) {
            addCriterion("LOGTC_NAME =", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameNotEqualTo(String value) {
            addCriterion("LOGTC_NAME <>", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameGreaterThan(String value) {
            addCriterion("LOGTC_NAME >", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOGTC_NAME >=", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameLessThan(String value) {
            addCriterion("LOGTC_NAME <", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameLessThanOrEqualTo(String value) {
            addCriterion("LOGTC_NAME <=", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameLike(String value) {
            addCriterion("LOGTC_NAME like", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameNotLike(String value) {
            addCriterion("LOGTC_NAME not like", value, "logtcName");
            return this;
        }

        public Criteria andLogtcNameIn(List values) {
            addCriterion("LOGTC_NAME in", values, "logtcName");
            return this;
        }

        public Criteria andLogtcNameNotIn(List values) {
            addCriterion("LOGTC_NAME not in", values, "logtcName");
            return this;
        }

        public Criteria andLogtcNameBetween(String value1, String value2) {
            addCriterion("LOGTC_NAME between", value1, value2, "logtcName");
            return this;
        }

        public Criteria andLogtcNameNotBetween(String value1, String value2) {
            addCriterion("LOGTC_NAME not between", value1, value2, "logtcName");
            return this;
        }

        public Criteria andLogicTypeIsNull() {
            addCriterion("LOGIC_TYPE is null");
            return this;
        }

        public Criteria andLogicTypeIsNotNull() {
            addCriterion("LOGIC_TYPE is not null");
            return this;
        }

        public Criteria andLogicTypeEqualTo(Integer value) {
            addCriterion("LOGIC_TYPE =", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeNotEqualTo(Integer value) {
            addCriterion("LOGIC_TYPE <>", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeGreaterThan(Integer value) {
            addCriterion("LOGIC_TYPE >", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOGIC_TYPE >=", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeLessThan(Integer value) {
            addCriterion("LOGIC_TYPE <", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeLessThanOrEqualTo(Integer value) {
            addCriterion("LOGIC_TYPE <=", value, "logicType");
            return this;
        }

        public Criteria andLogicTypeIn(List values) {
            addCriterion("LOGIC_TYPE in", values, "logicType");
            return this;
        }

        public Criteria andLogicTypeNotIn(List values) {
            addCriterion("LOGIC_TYPE not in", values, "logicType");
            return this;
        }

        public Criteria andLogicTypeBetween(Integer value1, Integer value2) {
            addCriterion("LOGIC_TYPE between", value1, value2, "logicType");
            return this;
        }

        public Criteria andLogicTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("LOGIC_TYPE not between", value1, value2, "logicType");
            return this;
        }

        public Criteria andIsSendIsNull() {
            addCriterion("IS_SEND is null");
            return this;
        }

        public Criteria andIsSendIsNotNull() {
            addCriterion("IS_SEND is not null");
            return this;
        }

        public Criteria andIsSendEqualTo(Integer value) {
            addCriterion("IS_SEND =", value, "isSend");
            return this;
        }

        public Criteria andIsSendNotEqualTo(Integer value) {
            addCriterion("IS_SEND <>", value, "isSend");
            return this;
        }

        public Criteria andIsSendGreaterThan(Integer value) {
            addCriterion("IS_SEND >", value, "isSend");
            return this;
        }

        public Criteria andIsSendGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_SEND >=", value, "isSend");
            return this;
        }

        public Criteria andIsSendLessThan(Integer value) {
            addCriterion("IS_SEND <", value, "isSend");
            return this;
        }

        public Criteria andIsSendLessThanOrEqualTo(Integer value) {
            addCriterion("IS_SEND <=", value, "isSend");
            return this;
        }

        public Criteria andIsSendIn(List values) {
            addCriterion("IS_SEND in", values, "isSend");
            return this;
        }

        public Criteria andIsSendNotIn(List values) {
            addCriterion("IS_SEND not in", values, "isSend");
            return this;
        }

        public Criteria andIsSendBetween(Integer value1, Integer value2) {
            addCriterion("IS_SEND between", value1, value2, "isSend");
            return this;
        }

        public Criteria andIsSendNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_SEND not between", value1, value2, "isSend");
            return this;
        }

        public Criteria andIsReceiveIsNull() {
            addCriterion("IS_RECEIVE is null");
            return this;
        }

        public Criteria andIsReceiveIsNotNull() {
            addCriterion("IS_RECEIVE is not null");
            return this;
        }

        public Criteria andIsReceiveEqualTo(Integer value) {
            addCriterion("IS_RECEIVE =", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveNotEqualTo(Integer value) {
            addCriterion("IS_RECEIVE <>", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveGreaterThan(Integer value) {
            addCriterion("IS_RECEIVE >", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_RECEIVE >=", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveLessThan(Integer value) {
            addCriterion("IS_RECEIVE <", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveLessThanOrEqualTo(Integer value) {
            addCriterion("IS_RECEIVE <=", value, "isReceive");
            return this;
        }

        public Criteria andIsReceiveIn(List values) {
            addCriterion("IS_RECEIVE in", values, "isReceive");
            return this;
        }

        public Criteria andIsReceiveNotIn(List values) {
            addCriterion("IS_RECEIVE not in", values, "isReceive");
            return this;
        }

        public Criteria andIsReceiveBetween(Integer value1, Integer value2) {
            addCriterion("IS_RECEIVE between", value1, value2, "isReceive");
            return this;
        }

        public Criteria andIsReceiveNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_RECEIVE not between", value1, value2, "isReceive");
            return this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andLogtcPriceIsNull() {
            addCriterion("LOGTC_PRICE is null");
            return this;
        }

        public Criteria andLogtcPriceIsNotNull() {
            addCriterion("LOGTC_PRICE is not null");
            return this;
        }

        public Criteria andLogtcPriceEqualTo(BigDecimal value) {
            addCriterion("LOGTC_PRICE =", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceNotEqualTo(BigDecimal value) {
            addCriterion("LOGTC_PRICE <>", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceGreaterThan(BigDecimal value) {
            addCriterion("LOGTC_PRICE >", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGTC_PRICE >=", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceLessThan(BigDecimal value) {
            addCriterion("LOGTC_PRICE <", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGTC_PRICE <=", value, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceIn(List values) {
            addCriterion("LOGTC_PRICE in", values, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceNotIn(List values) {
            addCriterion("LOGTC_PRICE not in", values, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGTC_PRICE between", value1, value2, "logtcPrice");
            return this;
        }

        public Criteria andLogtcPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGTC_PRICE not between", value1, value2, "logtcPrice");
            return this;
        }
    }
}