package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_receive_address", Class = BizAgentReceiveAddress.class)
public class BizAgentReceiveAddress<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.USER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.MOBILE_PHONE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String mobilePhone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.PROVINCE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.CITY
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.STREET
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String street;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.IS_DEFAULT
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Integer isDefault;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.USER_ID
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.SN
     *
     * @return the value of biz_agent_receive_address.SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.SN
     *
     * @param sn the value for biz_agent_receive_address.SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.USER_NAME
     *
     * @return the value of biz_agent_receive_address.USER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.USER_NAME
     *
     * @param userName the value for biz_agent_receive_address.USER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.MOBILE_PHONE
     *
     * @return the value of biz_agent_receive_address.MOBILE_PHONE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.MOBILE_PHONE
     *
     * @param mobilePhone the value for biz_agent_receive_address.MOBILE_PHONE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.PROVINCE
     *
     * @return the value of biz_agent_receive_address.PROVINCE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.PROVINCE
     *
     * @param province the value for biz_agent_receive_address.PROVINCE
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.CITY
     *
     * @return the value of biz_agent_receive_address.CITY
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.CITY
     *
     * @param city the value for biz_agent_receive_address.CITY
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.STREET
     *
     * @return the value of biz_agent_receive_address.STREET
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.STREET
     *
     * @param street the value for biz_agent_receive_address.STREET
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.IS_DEFAULT
     *
     * @return the value of biz_agent_receive_address.IS_DEFAULT
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.IS_DEFAULT
     *
     * @param isDefault the value for biz_agent_receive_address.IS_DEFAULT
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.USER_ID
     *
     * @return the value of biz_agent_receive_address.USER_ID
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.USER_ID
     *
     * @param userId the value for biz_agent_receive_address.USER_ID
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.ADDER_SN
     *
     * @return the value of biz_agent_receive_address.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.ADDER_SN
     *
     * @param adderSn the value for biz_agent_receive_address.ADDER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.ADDER_NAME
     *
     * @return the value of biz_agent_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.ADDER_NAME
     *
     * @param adderName the value for biz_agent_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.ADD_TIME
     *
     * @return the value of biz_agent_receive_address.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.ADD_TIME
     *
     * @param addTime the value for biz_agent_receive_address.ADD_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.UPDATER_SN
     *
     * @return the value of biz_agent_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.UPDATER_NAME
     *
     * @return the value of biz_agent_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_receive_address.UPDATE_TIME
     *
     * @return the value of biz_agent_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_receive_address.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Mon May 23 11:50:03 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}