package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_order_logtc", Class = BizAgentOrderLogtc.class)
public class BizAgentOrderLogtc<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.LOGTC_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private String logtcId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.LOGTC_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private String logtcName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.LOGIC_TYPE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Integer logicType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.IS_SEND
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Integer isSend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.IS_RECEIVE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Integer isReceive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Long orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_logtc.LOGTC_PRICE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    @Column
    private BigDecimal logtcPrice;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.SN
     *
     * @return the value of biz_agent_order_logtc.SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.SN
     *
     * @param sn the value for biz_agent_order_logtc.SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.LOGTC_ID
     *
     * @return the value of biz_agent_order_logtc.LOGTC_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public String getLogtcId() {
        return logtcId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.LOGTC_ID
     *
     * @param logtcId the value for biz_agent_order_logtc.LOGTC_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setLogtcId(String logtcId) {
        this.logtcId = logtcId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.LOGTC_NAME
     *
     * @return the value of biz_agent_order_logtc.LOGTC_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public String getLogtcName() {
        return logtcName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.LOGTC_NAME
     *
     * @param logtcName the value for biz_agent_order_logtc.LOGTC_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setLogtcName(String logtcName) {
        this.logtcName = logtcName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.LOGIC_TYPE
     *
     * @return the value of biz_agent_order_logtc.LOGIC_TYPE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Integer getLogicType() {
        return logicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.LOGIC_TYPE
     *
     * @param logicType the value for biz_agent_order_logtc.LOGIC_TYPE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setLogicType(Integer logicType) {
        this.logicType = logicType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.IS_SEND
     *
     * @return the value of biz_agent_order_logtc.IS_SEND
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.IS_SEND
     *
     * @param isSend the value for biz_agent_order_logtc.IS_SEND
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.IS_RECEIVE
     *
     * @return the value of biz_agent_order_logtc.IS_RECEIVE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Integer getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.IS_RECEIVE
     *
     * @param isReceive the value for biz_agent_order_logtc.IS_RECEIVE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setIsReceive(Integer isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.ORDER_ID
     *
     * @return the value of biz_agent_order_logtc.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.ORDER_ID
     *
     * @param orderId the value for biz_agent_order_logtc.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.ADDER_SN
     *
     * @return the value of biz_agent_order_logtc.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.ADDER_SN
     *
     * @param adderSn the value for biz_agent_order_logtc.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.ADDER_NAME
     *
     * @return the value of biz_agent_order_logtc.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.ADDER_NAME
     *
     * @param adderName the value for biz_agent_order_logtc.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.ADD_TIME
     *
     * @return the value of biz_agent_order_logtc.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.ADD_TIME
     *
     * @param addTime the value for biz_agent_order_logtc.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.UPDATER_SN
     *
     * @return the value of biz_agent_order_logtc.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_order_logtc.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.UPDATER_NAME
     *
     * @return the value of biz_agent_order_logtc.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_order_logtc.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.UPDATE_TIME
     *
     * @return the value of biz_agent_order_logtc.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_order_logtc.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_logtc.LOGTC_PRICE
     *
     * @return the value of biz_agent_order_logtc.LOGTC_PRICE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public BigDecimal getLogtcPrice() {
        return logtcPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_logtc.LOGTC_PRICE
     *
     * @param logtcPrice the value for biz_agent_order_logtc.LOGTC_PRICE
     *
     * @ibatorgenerated Thu Aug 11 14:54:54 CST 2016
     */
    public void setLogtcPrice(BigDecimal logtcPrice) {
        this.logtcPrice = logtcPrice;
    }
}