package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_order_item", Class = BizAgentOrderItem.class)
public class BizAgentOrderItem<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.PRODUCT_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Long productId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ITEM_AMOUNT
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Integer itemAmount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ITEM_PRICE
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private BigDecimal itemPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Long orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_item.PRODUCT_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    @Column
    private String productName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.SN
     *
     * @return the value of biz_agent_order_item.SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.SN
     *
     * @param sn the value for biz_agent_order_item.SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.PRODUCT_ID
     *
     * @return the value of biz_agent_order_item.PRODUCT_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.PRODUCT_ID
     *
     * @param productId the value for biz_agent_order_item.PRODUCT_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ITEM_AMOUNT
     *
     * @return the value of biz_agent_order_item.ITEM_AMOUNT
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Integer getItemAmount() {
        return itemAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ITEM_AMOUNT
     *
     * @param itemAmount the value for biz_agent_order_item.ITEM_AMOUNT
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setItemAmount(Integer itemAmount) {
        this.itemAmount = itemAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ITEM_PRICE
     *
     * @return the value of biz_agent_order_item.ITEM_PRICE
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ITEM_PRICE
     *
     * @param itemPrice the value for biz_agent_order_item.ITEM_PRICE
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ORDER_ID
     *
     * @return the value of biz_agent_order_item.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ORDER_ID
     *
     * @param orderId the value for biz_agent_order_item.ORDER_ID
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ADDER_SN
     *
     * @return the value of biz_agent_order_item.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ADDER_SN
     *
     * @param adderSn the value for biz_agent_order_item.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ADDER_NAME
     *
     * @return the value of biz_agent_order_item.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ADDER_NAME
     *
     * @param adderName the value for biz_agent_order_item.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.ADD_TIME
     *
     * @return the value of biz_agent_order_item.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.ADD_TIME
     *
     * @param addTime the value for biz_agent_order_item.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.UPDATER_SN
     *
     * @return the value of biz_agent_order_item.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_order_item.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.UPDATER_NAME
     *
     * @return the value of biz_agent_order_item.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_order_item.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.UPDATE_TIME
     *
     * @return the value of biz_agent_order_item.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_order_item.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_item.PRODUCT_NAME
     *
     * @return the value of biz_agent_order_item.PRODUCT_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_item.PRODUCT_NAME
     *
     * @param productName the value for biz_agent_order_item.PRODUCT_NAME
     *
     * @ibatorgenerated Thu Aug 11 12:34:17 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }
}