package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_product", Class = BizAgentProduct.class)
public class BizAgentProduct<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.TAG_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private String tagName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.PRICE
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private BigDecimal price;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.STATUS
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.REMARK
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.ADDER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.ADDER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.ADD_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.UPDATER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.UPDATER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_product.UPDATE_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.SN
     *
     * @return the value of biz_agent_product.SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.SN
     *
     * @param sn the value for biz_agent_product.SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.NAME
     *
     * @return the value of biz_agent_product.NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.NAME
     *
     * @param name the value for biz_agent_product.NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.TAG_NAME
     *
     * @return the value of biz_agent_product.TAG_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.TAG_NAME
     *
     * @param tagName the value for biz_agent_product.TAG_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.PRICE
     *
     * @return the value of biz_agent_product.PRICE
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.PRICE
     *
     * @param price the value for biz_agent_product.PRICE
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.STATUS
     *
     * @return the value of biz_agent_product.STATUS
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.STATUS
     *
     * @param status the value for biz_agent_product.STATUS
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.REMARK
     *
     * @return the value of biz_agent_product.REMARK
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.REMARK
     *
     * @param remark the value for biz_agent_product.REMARK
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.ADDER_SN
     *
     * @return the value of biz_agent_product.ADDER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.ADDER_SN
     *
     * @param adderSn the value for biz_agent_product.ADDER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.ADDER_NAME
     *
     * @return the value of biz_agent_product.ADDER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.ADDER_NAME
     *
     * @param adderName the value for biz_agent_product.ADDER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.ADD_TIME
     *
     * @return the value of biz_agent_product.ADD_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.ADD_TIME
     *
     * @param addTime the value for biz_agent_product.ADD_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.UPDATER_SN
     *
     * @return the value of biz_agent_product.UPDATER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_product.UPDATER_SN
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.UPDATER_NAME
     *
     * @return the value of biz_agent_product.UPDATER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_product.UPDATER_NAME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_product.UPDATE_TIME
     *
     * @return the value of biz_agent_product.UPDATE_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_product.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_product.UPDATE_TIME
     *
     * @ibatorgenerated Fri May 20 10:52:07 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}