package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_order_trans", Class = BizAgentOrderTrans.class)
public class BizAgentOrderTrans<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.ORDER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.BANK_CODE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String bankCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.BANK_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String bankName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_DATE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Date transDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String transType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_PLATFORM_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Integer transPlatformType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_ACCOUNT
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String transAccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_MONEY
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private BigDecimal transMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.MER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String merId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.CURRENCY_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String currencyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String transStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.TRANS_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String transId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.ADDER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.ADDER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.ADD_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.UPDATER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.UPDATER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order_trans.UPDATE_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.SN
     *
     * @return the value of biz_agent_order_trans.SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.SN
     *
     * @param sn the value for biz_agent_order_trans.SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.ORDER_ID
     *
     * @return the value of biz_agent_order_trans.ORDER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.ORDER_ID
     *
     * @param orderId the value for biz_agent_order_trans.ORDER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.BANK_CODE
     *
     * @return the value of biz_agent_order_trans.BANK_CODE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.BANK_CODE
     *
     * @param bankCode the value for biz_agent_order_trans.BANK_CODE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.BANK_NAME
     *
     * @return the value of biz_agent_order_trans.BANK_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.BANK_NAME
     *
     * @param bankName the value for biz_agent_order_trans.BANK_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_DATE
     *
     * @return the value of biz_agent_order_trans.TRANS_DATE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Date getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_DATE
     *
     * @param transDate the value for biz_agent_order_trans.TRANS_DATE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_TYPE
     *
     * @return the value of biz_agent_order_trans.TRANS_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_TYPE
     *
     * @param transType the value for biz_agent_order_trans.TRANS_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_PLATFORM_TYPE
     *
     * @return the value of biz_agent_order_trans.TRANS_PLATFORM_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Integer getTransPlatformType() {
        return transPlatformType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_PLATFORM_TYPE
     *
     * @param transPlatformType the value for biz_agent_order_trans.TRANS_PLATFORM_TYPE
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransPlatformType(Integer transPlatformType) {
        this.transPlatformType = transPlatformType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_ACCOUNT
     *
     * @return the value of biz_agent_order_trans.TRANS_ACCOUNT
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getTransAccount() {
        return transAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_ACCOUNT
     *
     * @param transAccount the value for biz_agent_order_trans.TRANS_ACCOUNT
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransAccount(String transAccount) {
        this.transAccount = transAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_MONEY
     *
     * @return the value of biz_agent_order_trans.TRANS_MONEY
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public BigDecimal getTransMoney() {
        return transMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_MONEY
     *
     * @param transMoney the value for biz_agent_order_trans.TRANS_MONEY
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransMoney(BigDecimal transMoney) {
        this.transMoney = transMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.MER_ID
     *
     * @return the value of biz_agent_order_trans.MER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.MER_ID
     *
     * @param merId the value for biz_agent_order_trans.MER_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setMerId(String merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.CURRENCY_ID
     *
     * @return the value of biz_agent_order_trans.CURRENCY_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.CURRENCY_ID
     *
     * @param currencyId the value for biz_agent_order_trans.CURRENCY_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setCurrencyId(String currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_STATUS
     *
     * @return the value of biz_agent_order_trans.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_STATUS
     *
     * @param transStatus the value for biz_agent_order_trans.TRANS_STATUS
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.TRANS_ID
     *
     * @return the value of biz_agent_order_trans.TRANS_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.TRANS_ID
     *
     * @param transId the value for biz_agent_order_trans.TRANS_ID
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setTransId(String transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.ADDER_SN
     *
     * @return the value of biz_agent_order_trans.ADDER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.ADDER_SN
     *
     * @param adderSn the value for biz_agent_order_trans.ADDER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.ADDER_NAME
     *
     * @return the value of biz_agent_order_trans.ADDER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.ADDER_NAME
     *
     * @param adderName the value for biz_agent_order_trans.ADDER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.ADD_TIME
     *
     * @return the value of biz_agent_order_trans.ADD_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.ADD_TIME
     *
     * @param addTime the value for biz_agent_order_trans.ADD_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.UPDATER_SN
     *
     * @return the value of biz_agent_order_trans.UPDATER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_order_trans.UPDATER_SN
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.UPDATER_NAME
     *
     * @return the value of biz_agent_order_trans.UPDATER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_order_trans.UPDATER_NAME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order_trans.UPDATE_TIME
     *
     * @return the value of biz_agent_order_trans.UPDATE_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order_trans.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_order_trans.UPDATE_TIME
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}