package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_agent_order", Class = BizAgentOrder.class)
public class BizAgentOrderCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public BizAgentOrderCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public BizAgentOrderCriteria(BizAgentOrderCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public BizAgentOrderCriteria(Object record, BizAgentOrderCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_agent_order
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("ORDER_NUM is null");
            return this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("ORDER_NUM is not null");
            return this;
        }

        public Criteria andOrderNumEqualTo(String value) {
            addCriterion("ORDER_NUM =", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotEqualTo(String value) {
            addCriterion("ORDER_NUM <>", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThan(String value) {
            addCriterion("ORDER_NUM >", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM >=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThan(String value) {
            addCriterion("ORDER_NUM <", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM <=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLike(String value) {
            addCriterion("ORDER_NUM like", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotLike(String value) {
            addCriterion("ORDER_NUM not like", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumIn(List values) {
            addCriterion("ORDER_NUM in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotIn(List values) {
            addCriterion("ORDER_NUM not in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumBetween(String value1, String value2) {
            addCriterion("ORDER_NUM between", value1, value2, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotBetween(String value1, String value2) {
            addCriterion("ORDER_NUM not between", value1, value2, "orderNum");
            return this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("ORDER_TIME is null");
            return this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("ORDER_TIME is not null");
            return this;
        }

        public Criteria andOrderTimeEqualTo(Date value) {
            addCriterion("ORDER_TIME =", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotEqualTo(Date value) {
            addCriterion("ORDER_TIME <>", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThan(Date value) {
            addCriterion("ORDER_TIME >", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ORDER_TIME >=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThan(Date value) {
            addCriterion("ORDER_TIME <", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("ORDER_TIME <=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeIn(List values) {
            addCriterion("ORDER_TIME in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotIn(List values) {
            addCriterion("ORDER_TIME not in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeBetween(Date value1, Date value2) {
            addCriterion("ORDER_TIME between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("ORDER_TIME not between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andReceiveAddressIdIsNull() {
            addCriterion("RECEIVE_ADDRESS_ID is null");
            return this;
        }

        public Criteria andReceiveAddressIdIsNotNull() {
            addCriterion("RECEIVE_ADDRESS_ID is not null");
            return this;
        }

        public Criteria andReceiveAddressIdEqualTo(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID =", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdNotEqualTo(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID <>", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdGreaterThan(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID >", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID >=", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdLessThan(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID <", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdLessThanOrEqualTo(Long value) {
            addCriterion("RECEIVE_ADDRESS_ID <=", value, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdIn(List values) {
            addCriterion("RECEIVE_ADDRESS_ID in", values, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdNotIn(List values) {
            addCriterion("RECEIVE_ADDRESS_ID not in", values, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdBetween(Long value1, Long value2) {
            addCriterion("RECEIVE_ADDRESS_ID between", value1, value2, "receiveAddressId");
            return this;
        }

        public Criteria andReceiveAddressIdNotBetween(Long value1, Long value2) {
            addCriterion("RECEIVE_ADDRESS_ID not between", value1, value2, "receiveAddressId");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("TOTAL_PRICE is null");
            return this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("TOTAL_PRICE is not null");
            return this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE =", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <>", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE >", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE >=", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE <", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <=", value, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceIn(List values) {
            addCriterion("TOTAL_PRICE in", values, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceNotIn(List values) {
            addCriterion("TOTAL_PRICE not in", values, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE between", value1, value2, "totalPrice");
            return this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE not between", value1, value2, "totalPrice");
            return this;
        }

        public Criteria andIsInvoiceIsNull() {
            addCriterion("IS_INVOICE is null");
            return this;
        }

        public Criteria andIsInvoiceIsNotNull() {
            addCriterion("IS_INVOICE is not null");
            return this;
        }

        public Criteria andIsInvoiceEqualTo(Integer value) {
            addCriterion("IS_INVOICE =", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceNotEqualTo(Integer value) {
            addCriterion("IS_INVOICE <>", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceGreaterThan(Integer value) {
            addCriterion("IS_INVOICE >", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_INVOICE >=", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceLessThan(Integer value) {
            addCriterion("IS_INVOICE <", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceLessThanOrEqualTo(Integer value) {
            addCriterion("IS_INVOICE <=", value, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceIn(List values) {
            addCriterion("IS_INVOICE in", values, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceNotIn(List values) {
            addCriterion("IS_INVOICE not in", values, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceBetween(Integer value1, Integer value2) {
            addCriterion("IS_INVOICE between", value1, value2, "isInvoice");
            return this;
        }

        public Criteria andIsInvoiceNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_INVOICE not between", value1, value2, "isInvoice");
            return this;
        }

        public Criteria andInvoiceTypeIsNull() {
            addCriterion("INVOICE_TYPE is null");
            return this;
        }

        public Criteria andInvoiceTypeIsNotNull() {
            addCriterion("INVOICE_TYPE is not null");
            return this;
        }

        public Criteria andInvoiceTypeEqualTo(Integer value) {
            addCriterion("INVOICE_TYPE =", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeNotEqualTo(Integer value) {
            addCriterion("INVOICE_TYPE <>", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeGreaterThan(Integer value) {
            addCriterion("INVOICE_TYPE >", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("INVOICE_TYPE >=", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeLessThan(Integer value) {
            addCriterion("INVOICE_TYPE <", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("INVOICE_TYPE <=", value, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeIn(List values) {
            addCriterion("INVOICE_TYPE in", values, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeNotIn(List values) {
            addCriterion("INVOICE_TYPE not in", values, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeBetween(Integer value1, Integer value2) {
            addCriterion("INVOICE_TYPE between", value1, value2, "invoiceType");
            return this;
        }

        public Criteria andInvoiceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("INVOICE_TYPE not between", value1, value2, "invoiceType");
            return this;
        }

        public Criteria andInvoiceHeadIsNull() {
            addCriterion("INVOICE_HEAD is null");
            return this;
        }

        public Criteria andInvoiceHeadIsNotNull() {
            addCriterion("INVOICE_HEAD is not null");
            return this;
        }

        public Criteria andInvoiceHeadEqualTo(String value) {
            addCriterion("INVOICE_HEAD =", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadNotEqualTo(String value) {
            addCriterion("INVOICE_HEAD <>", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadGreaterThan(String value) {
            addCriterion("INVOICE_HEAD >", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_HEAD >=", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadLessThan(String value) {
            addCriterion("INVOICE_HEAD <", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_HEAD <=", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadLike(String value) {
            addCriterion("INVOICE_HEAD like", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadNotLike(String value) {
            addCriterion("INVOICE_HEAD not like", value, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadIn(List values) {
            addCriterion("INVOICE_HEAD in", values, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadNotIn(List values) {
            addCriterion("INVOICE_HEAD not in", values, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadBetween(String value1, String value2) {
            addCriterion("INVOICE_HEAD between", value1, value2, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceHeadNotBetween(String value1, String value2) {
            addCriterion("INVOICE_HEAD not between", value1, value2, "invoiceHead");
            return this;
        }

        public Criteria andInvoiceCompanyNameIsNull() {
            addCriterion("INVOICE_COMPANY_NAME is null");
            return this;
        }

        public Criteria andInvoiceCompanyNameIsNotNull() {
            addCriterion("INVOICE_COMPANY_NAME is not null");
            return this;
        }

        public Criteria andInvoiceCompanyNameEqualTo(String value) {
            addCriterion("INVOICE_COMPANY_NAME =", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameNotEqualTo(String value) {
            addCriterion("INVOICE_COMPANY_NAME <>", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameGreaterThan(String value) {
            addCriterion("INVOICE_COMPANY_NAME >", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_COMPANY_NAME >=", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameLessThan(String value) {
            addCriterion("INVOICE_COMPANY_NAME <", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_COMPANY_NAME <=", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameLike(String value) {
            addCriterion("INVOICE_COMPANY_NAME like", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameNotLike(String value) {
            addCriterion("INVOICE_COMPANY_NAME not like", value, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameIn(List values) {
            addCriterion("INVOICE_COMPANY_NAME in", values, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameNotIn(List values) {
            addCriterion("INVOICE_COMPANY_NAME not in", values, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameBetween(String value1, String value2) {
            addCriterion("INVOICE_COMPANY_NAME between", value1, value2, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceCompanyNameNotBetween(String value1, String value2) {
            addCriterion("INVOICE_COMPANY_NAME not between", value1, value2, "invoiceCompanyName");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdIsNull() {
            addCriterion("INVOICE_TAXPAYER_ID is null");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdIsNotNull() {
            addCriterion("INVOICE_TAXPAYER_ID is not null");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdEqualTo(String value) {
            addCriterion("INVOICE_TAXPAYER_ID =", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdNotEqualTo(String value) {
            addCriterion("INVOICE_TAXPAYER_ID <>", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdGreaterThan(String value) {
            addCriterion("INVOICE_TAXPAYER_ID >", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_TAXPAYER_ID >=", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdLessThan(String value) {
            addCriterion("INVOICE_TAXPAYER_ID <", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_TAXPAYER_ID <=", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdLike(String value) {
            addCriterion("INVOICE_TAXPAYER_ID like", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdNotLike(String value) {
            addCriterion("INVOICE_TAXPAYER_ID not like", value, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdIn(List values) {
            addCriterion("INVOICE_TAXPAYER_ID in", values, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdNotIn(List values) {
            addCriterion("INVOICE_TAXPAYER_ID not in", values, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdBetween(String value1, String value2) {
            addCriterion("INVOICE_TAXPAYER_ID between", value1, value2, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceTaxpayerIdNotBetween(String value1, String value2) {
            addCriterion("INVOICE_TAXPAYER_ID not between", value1, value2, "invoiceTaxpayerId");
            return this;
        }

        public Criteria andInvoiceAddressIsNull() {
            addCriterion("INVOICE_ADDRESS is null");
            return this;
        }

        public Criteria andInvoiceAddressIsNotNull() {
            addCriterion("INVOICE_ADDRESS is not null");
            return this;
        }

        public Criteria andInvoiceAddressEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS =", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressNotEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS <>", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressGreaterThan(String value) {
            addCriterion("INVOICE_ADDRESS >", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS >=", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressLessThan(String value) {
            addCriterion("INVOICE_ADDRESS <", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS <=", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressLike(String value) {
            addCriterion("INVOICE_ADDRESS like", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressNotLike(String value) {
            addCriterion("INVOICE_ADDRESS not like", value, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressIn(List values) {
            addCriterion("INVOICE_ADDRESS in", values, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressNotIn(List values) {
            addCriterion("INVOICE_ADDRESS not in", values, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS between", value1, value2, "invoiceAddress");
            return this;
        }

        public Criteria andInvoiceAddressNotBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS not between", value1, value2, "invoiceAddress");
            return this;
        }

        public Criteria andInvoicePhoneIsNull() {
            addCriterion("INVOICE_PHONE is null");
            return this;
        }

        public Criteria andInvoicePhoneIsNotNull() {
            addCriterion("INVOICE_PHONE is not null");
            return this;
        }

        public Criteria andInvoicePhoneEqualTo(String value) {
            addCriterion("INVOICE_PHONE =", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneNotEqualTo(String value) {
            addCriterion("INVOICE_PHONE <>", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneGreaterThan(String value) {
            addCriterion("INVOICE_PHONE >", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_PHONE >=", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneLessThan(String value) {
            addCriterion("INVOICE_PHONE <", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_PHONE <=", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneLike(String value) {
            addCriterion("INVOICE_PHONE like", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneNotLike(String value) {
            addCriterion("INVOICE_PHONE not like", value, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneIn(List values) {
            addCriterion("INVOICE_PHONE in", values, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneNotIn(List values) {
            addCriterion("INVOICE_PHONE not in", values, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneBetween(String value1, String value2) {
            addCriterion("INVOICE_PHONE between", value1, value2, "invoicePhone");
            return this;
        }

        public Criteria andInvoicePhoneNotBetween(String value1, String value2) {
            addCriterion("INVOICE_PHONE not between", value1, value2, "invoicePhone");
            return this;
        }

        public Criteria andInvoiceBankNameIsNull() {
            addCriterion("INVOICE_BANK_NAME is null");
            return this;
        }

        public Criteria andInvoiceBankNameIsNotNull() {
            addCriterion("INVOICE_BANK_NAME is not null");
            return this;
        }

        public Criteria andInvoiceBankNameEqualTo(String value) {
            addCriterion("INVOICE_BANK_NAME =", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameNotEqualTo(String value) {
            addCriterion("INVOICE_BANK_NAME <>", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameGreaterThan(String value) {
            addCriterion("INVOICE_BANK_NAME >", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_BANK_NAME >=", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameLessThan(String value) {
            addCriterion("INVOICE_BANK_NAME <", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_BANK_NAME <=", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameLike(String value) {
            addCriterion("INVOICE_BANK_NAME like", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameNotLike(String value) {
            addCriterion("INVOICE_BANK_NAME not like", value, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameIn(List values) {
            addCriterion("INVOICE_BANK_NAME in", values, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameNotIn(List values) {
            addCriterion("INVOICE_BANK_NAME not in", values, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameBetween(String value1, String value2) {
            addCriterion("INVOICE_BANK_NAME between", value1, value2, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankNameNotBetween(String value1, String value2) {
            addCriterion("INVOICE_BANK_NAME not between", value1, value2, "invoiceBankName");
            return this;
        }

        public Criteria andInvoiceBankAccountIsNull() {
            addCriterion("INVOICE_BANK_ACCOUNT is null");
            return this;
        }

        public Criteria andInvoiceBankAccountIsNotNull() {
            addCriterion("INVOICE_BANK_ACCOUNT is not null");
            return this;
        }

        public Criteria andInvoiceBankAccountEqualTo(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT =", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountNotEqualTo(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT <>", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountGreaterThan(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT >", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT >=", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountLessThan(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT <", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT <=", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountLike(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT like", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountNotLike(String value) {
            addCriterion("INVOICE_BANK_ACCOUNT not like", value, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountIn(List values) {
            addCriterion("INVOICE_BANK_ACCOUNT in", values, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountNotIn(List values) {
            addCriterion("INVOICE_BANK_ACCOUNT not in", values, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountBetween(String value1, String value2) {
            addCriterion("INVOICE_BANK_ACCOUNT between", value1, value2, "invoiceBankAccount");
            return this;
        }

        public Criteria andInvoiceBankAccountNotBetween(String value1, String value2) {
            addCriterion("INVOICE_BANK_ACCOUNT not between", value1, value2, "invoiceBankAccount");
            return this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PAY_TIME is null");
            return this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PAY_TIME is not null");
            return this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("PAY_TIME =", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("PAY_TIME <>", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("PAY_TIME >", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PAY_TIME >=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("PAY_TIME <", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("PAY_TIME <=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeIn(List values) {
            addCriterion("PAY_TIME in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeNotIn(List values) {
            addCriterion("PAY_TIME not in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("PAY_TIME between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("PAY_TIME not between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPrepayIdIsNull() {
            addCriterion("PREPAY_ID is null");
            return this;
        }

        public Criteria andPrepayIdIsNotNull() {
            addCriterion("PREPAY_ID is not null");
            return this;
        }

        public Criteria andPrepayIdEqualTo(String value) {
            addCriterion("PREPAY_ID =", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotEqualTo(String value) {
            addCriterion("PREPAY_ID <>", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdGreaterThan(String value) {
            addCriterion("PREPAY_ID >", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdGreaterThanOrEqualTo(String value) {
            addCriterion("PREPAY_ID >=", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLessThan(String value) {
            addCriterion("PREPAY_ID <", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLessThanOrEqualTo(String value) {
            addCriterion("PREPAY_ID <=", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLike(String value) {
            addCriterion("PREPAY_ID like", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotLike(String value) {
            addCriterion("PREPAY_ID not like", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdIn(List values) {
            addCriterion("PREPAY_ID in", values, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotIn(List values) {
            addCriterion("PREPAY_ID not in", values, "prepayId");
            return this;
        }

        public Criteria andPrepayIdBetween(String value1, String value2) {
            addCriterion("PREPAY_ID between", value1, value2, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotBetween(String value1, String value2) {
            addCriterion("PREPAY_ID not between", value1, value2, "prepayId");
            return this;
        }

        public Criteria andQrFileSnIsNull() {
            addCriterion("QR_FILE_SN is null");
            return this;
        }

        public Criteria andQrFileSnIsNotNull() {
            addCriterion("QR_FILE_SN is not null");
            return this;
        }

        public Criteria andQrFileSnEqualTo(Long value) {
            addCriterion("QR_FILE_SN =", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnNotEqualTo(Long value) {
            addCriterion("QR_FILE_SN <>", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnGreaterThan(Long value) {
            addCriterion("QR_FILE_SN >", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("QR_FILE_SN >=", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnLessThan(Long value) {
            addCriterion("QR_FILE_SN <", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnLessThanOrEqualTo(Long value) {
            addCriterion("QR_FILE_SN <=", value, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnIn(List values) {
            addCriterion("QR_FILE_SN in", values, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnNotIn(List values) {
            addCriterion("QR_FILE_SN not in", values, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnBetween(Long value1, Long value2) {
            addCriterion("QR_FILE_SN between", value1, value2, "qrFileSn");
            return this;
        }

        public Criteria andQrFileSnNotBetween(Long value1, Long value2) {
            addCriterion("QR_FILE_SN not between", value1, value2, "qrFileSn");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andExtendIsNull() {
            addCriterion("EXTEND is null");
            return this;
        }

        public Criteria andExtendIsNotNull() {
            addCriterion("EXTEND is not null");
            return this;
        }

        public Criteria andExtendEqualTo(String value) {
            addCriterion("EXTEND =", value, "extend");
            return this;
        }

        public Criteria andExtendNotEqualTo(String value) {
            addCriterion("EXTEND <>", value, "extend");
            return this;
        }

        public Criteria andExtendGreaterThan(String value) {
            addCriterion("EXTEND >", value, "extend");
            return this;
        }

        public Criteria andExtendGreaterThanOrEqualTo(String value) {
            addCriterion("EXTEND >=", value, "extend");
            return this;
        }

        public Criteria andExtendLessThan(String value) {
            addCriterion("EXTEND <", value, "extend");
            return this;
        }

        public Criteria andExtendLessThanOrEqualTo(String value) {
            addCriterion("EXTEND <=", value, "extend");
            return this;
        }

        public Criteria andExtendLike(String value) {
            addCriterion("EXTEND like", value, "extend");
            return this;
        }

        public Criteria andExtendNotLike(String value) {
            addCriterion("EXTEND not like", value, "extend");
            return this;
        }

        public Criteria andExtendIn(List values) {
            addCriterion("EXTEND in", values, "extend");
            return this;
        }

        public Criteria andExtendNotIn(List values) {
            addCriterion("EXTEND not in", values, "extend");
            return this;
        }

        public Criteria andExtendBetween(String value1, String value2) {
            addCriterion("EXTEND between", value1, value2, "extend");
            return this;
        }

        public Criteria andExtendNotBetween(String value1, String value2) {
            addCriterion("EXTEND not between", value1, value2, "extend");
            return this;
        }
    }
}