package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_agent_order_trans", Class = BizAgentOrderTrans.class)
public class BizAgentOrderTransCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public BizAgentOrderTransCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public BizAgentOrderTransCriteria(BizAgentOrderTransCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public BizAgentOrderTransCriteria(Object record, BizAgentOrderTransCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_agent_order_trans
     *
     * @ibatorgenerated Tue May 24 12:42:40 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andBankCodeIsNull() {
            addCriterion("BANK_CODE is null");
            return this;
        }

        public Criteria andBankCodeIsNotNull() {
            addCriterion("BANK_CODE is not null");
            return this;
        }

        public Criteria andBankCodeEqualTo(String value) {
            addCriterion("BANK_CODE =", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeNotEqualTo(String value) {
            addCriterion("BANK_CODE <>", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeGreaterThan(String value) {
            addCriterion("BANK_CODE >", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_CODE >=", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeLessThan(String value) {
            addCriterion("BANK_CODE <", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeLessThanOrEqualTo(String value) {
            addCriterion("BANK_CODE <=", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeLike(String value) {
            addCriterion("BANK_CODE like", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeNotLike(String value) {
            addCriterion("BANK_CODE not like", value, "bankCode");
            return this;
        }

        public Criteria andBankCodeIn(List values) {
            addCriterion("BANK_CODE in", values, "bankCode");
            return this;
        }

        public Criteria andBankCodeNotIn(List values) {
            addCriterion("BANK_CODE not in", values, "bankCode");
            return this;
        }

        public Criteria andBankCodeBetween(String value1, String value2) {
            addCriterion("BANK_CODE between", value1, value2, "bankCode");
            return this;
        }

        public Criteria andBankCodeNotBetween(String value1, String value2) {
            addCriterion("BANK_CODE not between", value1, value2, "bankCode");
            return this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return this;
        }

        public Criteria andBankNameIn(List values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return this;
        }

        public Criteria andBankNameNotIn(List values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return this;
        }

        public Criteria andTransDateIsNull() {
            addCriterion("TRANS_DATE is null");
            return this;
        }

        public Criteria andTransDateIsNotNull() {
            addCriterion("TRANS_DATE is not null");
            return this;
        }

        public Criteria andTransDateEqualTo(Date value) {
            addCriterion("TRANS_DATE =", value, "transDate");
            return this;
        }

        public Criteria andTransDateNotEqualTo(Date value) {
            addCriterion("TRANS_DATE <>", value, "transDate");
            return this;
        }

        public Criteria andTransDateGreaterThan(Date value) {
            addCriterion("TRANS_DATE >", value, "transDate");
            return this;
        }

        public Criteria andTransDateGreaterThanOrEqualTo(Date value) {
            addCriterion("TRANS_DATE >=", value, "transDate");
            return this;
        }

        public Criteria andTransDateLessThan(Date value) {
            addCriterion("TRANS_DATE <", value, "transDate");
            return this;
        }

        public Criteria andTransDateLessThanOrEqualTo(Date value) {
            addCriterion("TRANS_DATE <=", value, "transDate");
            return this;
        }

        public Criteria andTransDateIn(List values) {
            addCriterion("TRANS_DATE in", values, "transDate");
            return this;
        }

        public Criteria andTransDateNotIn(List values) {
            addCriterion("TRANS_DATE not in", values, "transDate");
            return this;
        }

        public Criteria andTransDateBetween(Date value1, Date value2) {
            addCriterion("TRANS_DATE between", value1, value2, "transDate");
            return this;
        }

        public Criteria andTransDateNotBetween(Date value1, Date value2) {
            addCriterion("TRANS_DATE not between", value1, value2, "transDate");
            return this;
        }

        public Criteria andTransTypeIsNull() {
            addCriterion("TRANS_TYPE is null");
            return this;
        }

        public Criteria andTransTypeIsNotNull() {
            addCriterion("TRANS_TYPE is not null");
            return this;
        }

        public Criteria andTransTypeEqualTo(String value) {
            addCriterion("TRANS_TYPE =", value, "transType");
            return this;
        }

        public Criteria andTransTypeNotEqualTo(String value) {
            addCriterion("TRANS_TYPE <>", value, "transType");
            return this;
        }

        public Criteria andTransTypeGreaterThan(String value) {
            addCriterion("TRANS_TYPE >", value, "transType");
            return this;
        }

        public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_TYPE >=", value, "transType");
            return this;
        }

        public Criteria andTransTypeLessThan(String value) {
            addCriterion("TRANS_TYPE <", value, "transType");
            return this;
        }

        public Criteria andTransTypeLessThanOrEqualTo(String value) {
            addCriterion("TRANS_TYPE <=", value, "transType");
            return this;
        }

        public Criteria andTransTypeLike(String value) {
            addCriterion("TRANS_TYPE like", value, "transType");
            return this;
        }

        public Criteria andTransTypeNotLike(String value) {
            addCriterion("TRANS_TYPE not like", value, "transType");
            return this;
        }

        public Criteria andTransTypeIn(List values) {
            addCriterion("TRANS_TYPE in", values, "transType");
            return this;
        }

        public Criteria andTransTypeNotIn(List values) {
            addCriterion("TRANS_TYPE not in", values, "transType");
            return this;
        }

        public Criteria andTransTypeBetween(String value1, String value2) {
            addCriterion("TRANS_TYPE between", value1, value2, "transType");
            return this;
        }

        public Criteria andTransTypeNotBetween(String value1, String value2) {
            addCriterion("TRANS_TYPE not between", value1, value2, "transType");
            return this;
        }

        public Criteria andTransPlatformTypeIsNull() {
            addCriterion("TRANS_PLATFORM_TYPE is null");
            return this;
        }

        public Criteria andTransPlatformTypeIsNotNull() {
            addCriterion("TRANS_PLATFORM_TYPE is not null");
            return this;
        }

        public Criteria andTransPlatformTypeEqualTo(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE =", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeNotEqualTo(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE <>", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeGreaterThan(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE >", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE >=", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeLessThan(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE <", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TRANS_PLATFORM_TYPE <=", value, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeIn(List values) {
            addCriterion("TRANS_PLATFORM_TYPE in", values, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeNotIn(List values) {
            addCriterion("TRANS_PLATFORM_TYPE not in", values, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeBetween(Integer value1, Integer value2) {
            addCriterion("TRANS_PLATFORM_TYPE between", value1, value2, "transPlatformType");
            return this;
        }

        public Criteria andTransPlatformTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TRANS_PLATFORM_TYPE not between", value1, value2, "transPlatformType");
            return this;
        }

        public Criteria andTransAccountIsNull() {
            addCriterion("TRANS_ACCOUNT is null");
            return this;
        }

        public Criteria andTransAccountIsNotNull() {
            addCriterion("TRANS_ACCOUNT is not null");
            return this;
        }

        public Criteria andTransAccountEqualTo(String value) {
            addCriterion("TRANS_ACCOUNT =", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountNotEqualTo(String value) {
            addCriterion("TRANS_ACCOUNT <>", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountGreaterThan(String value) {
            addCriterion("TRANS_ACCOUNT >", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_ACCOUNT >=", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountLessThan(String value) {
            addCriterion("TRANS_ACCOUNT <", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountLessThanOrEqualTo(String value) {
            addCriterion("TRANS_ACCOUNT <=", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountLike(String value) {
            addCriterion("TRANS_ACCOUNT like", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountNotLike(String value) {
            addCriterion("TRANS_ACCOUNT not like", value, "transAccount");
            return this;
        }

        public Criteria andTransAccountIn(List values) {
            addCriterion("TRANS_ACCOUNT in", values, "transAccount");
            return this;
        }

        public Criteria andTransAccountNotIn(List values) {
            addCriterion("TRANS_ACCOUNT not in", values, "transAccount");
            return this;
        }

        public Criteria andTransAccountBetween(String value1, String value2) {
            addCriterion("TRANS_ACCOUNT between", value1, value2, "transAccount");
            return this;
        }

        public Criteria andTransAccountNotBetween(String value1, String value2) {
            addCriterion("TRANS_ACCOUNT not between", value1, value2, "transAccount");
            return this;
        }

        public Criteria andTransMoneyIsNull() {
            addCriterion("TRANS_MONEY is null");
            return this;
        }

        public Criteria andTransMoneyIsNotNull() {
            addCriterion("TRANS_MONEY is not null");
            return this;
        }

        public Criteria andTransMoneyEqualTo(BigDecimal value) {
            addCriterion("TRANS_MONEY =", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyNotEqualTo(BigDecimal value) {
            addCriterion("TRANS_MONEY <>", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyGreaterThan(BigDecimal value) {
            addCriterion("TRANS_MONEY >", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANS_MONEY >=", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyLessThan(BigDecimal value) {
            addCriterion("TRANS_MONEY <", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANS_MONEY <=", value, "transMoney");
            return this;
        }

        public Criteria andTransMoneyIn(List values) {
            addCriterion("TRANS_MONEY in", values, "transMoney");
            return this;
        }

        public Criteria andTransMoneyNotIn(List values) {
            addCriterion("TRANS_MONEY not in", values, "transMoney");
            return this;
        }

        public Criteria andTransMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANS_MONEY between", value1, value2, "transMoney");
            return this;
        }

        public Criteria andTransMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANS_MONEY not between", value1, value2, "transMoney");
            return this;
        }

        public Criteria andMerIdIsNull() {
            addCriterion("MER_ID is null");
            return this;
        }

        public Criteria andMerIdIsNotNull() {
            addCriterion("MER_ID is not null");
            return this;
        }

        public Criteria andMerIdEqualTo(String value) {
            addCriterion("MER_ID =", value, "merId");
            return this;
        }

        public Criteria andMerIdNotEqualTo(String value) {
            addCriterion("MER_ID <>", value, "merId");
            return this;
        }

        public Criteria andMerIdGreaterThan(String value) {
            addCriterion("MER_ID >", value, "merId");
            return this;
        }

        public Criteria andMerIdGreaterThanOrEqualTo(String value) {
            addCriterion("MER_ID >=", value, "merId");
            return this;
        }

        public Criteria andMerIdLessThan(String value) {
            addCriterion("MER_ID <", value, "merId");
            return this;
        }

        public Criteria andMerIdLessThanOrEqualTo(String value) {
            addCriterion("MER_ID <=", value, "merId");
            return this;
        }

        public Criteria andMerIdLike(String value) {
            addCriterion("MER_ID like", value, "merId");
            return this;
        }

        public Criteria andMerIdNotLike(String value) {
            addCriterion("MER_ID not like", value, "merId");
            return this;
        }

        public Criteria andMerIdIn(List values) {
            addCriterion("MER_ID in", values, "merId");
            return this;
        }

        public Criteria andMerIdNotIn(List values) {
            addCriterion("MER_ID not in", values, "merId");
            return this;
        }

        public Criteria andMerIdBetween(String value1, String value2) {
            addCriterion("MER_ID between", value1, value2, "merId");
            return this;
        }

        public Criteria andMerIdNotBetween(String value1, String value2) {
            addCriterion("MER_ID not between", value1, value2, "merId");
            return this;
        }

        public Criteria andCurrencyIdIsNull() {
            addCriterion("CURRENCY_ID is null");
            return this;
        }

        public Criteria andCurrencyIdIsNotNull() {
            addCriterion("CURRENCY_ID is not null");
            return this;
        }

        public Criteria andCurrencyIdEqualTo(String value) {
            addCriterion("CURRENCY_ID =", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotEqualTo(String value) {
            addCriterion("CURRENCY_ID <>", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdGreaterThan(String value) {
            addCriterion("CURRENCY_ID >", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_ID >=", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLessThan(String value) {
            addCriterion("CURRENCY_ID <", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_ID <=", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLike(String value) {
            addCriterion("CURRENCY_ID like", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotLike(String value) {
            addCriterion("CURRENCY_ID not like", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdIn(List values) {
            addCriterion("CURRENCY_ID in", values, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotIn(List values) {
            addCriterion("CURRENCY_ID not in", values, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdBetween(String value1, String value2) {
            addCriterion("CURRENCY_ID between", value1, value2, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_ID not between", value1, value2, "currencyId");
            return this;
        }

        public Criteria andTransStatusIsNull() {
            addCriterion("TRANS_STATUS is null");
            return this;
        }

        public Criteria andTransStatusIsNotNull() {
            addCriterion("TRANS_STATUS is not null");
            return this;
        }

        public Criteria andTransStatusEqualTo(String value) {
            addCriterion("TRANS_STATUS =", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusNotEqualTo(String value) {
            addCriterion("TRANS_STATUS <>", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusGreaterThan(String value) {
            addCriterion("TRANS_STATUS >", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_STATUS >=", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusLessThan(String value) {
            addCriterion("TRANS_STATUS <", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusLessThanOrEqualTo(String value) {
            addCriterion("TRANS_STATUS <=", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusLike(String value) {
            addCriterion("TRANS_STATUS like", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusNotLike(String value) {
            addCriterion("TRANS_STATUS not like", value, "transStatus");
            return this;
        }

        public Criteria andTransStatusIn(List values) {
            addCriterion("TRANS_STATUS in", values, "transStatus");
            return this;
        }

        public Criteria andTransStatusNotIn(List values) {
            addCriterion("TRANS_STATUS not in", values, "transStatus");
            return this;
        }

        public Criteria andTransStatusBetween(String value1, String value2) {
            addCriterion("TRANS_STATUS between", value1, value2, "transStatus");
            return this;
        }

        public Criteria andTransStatusNotBetween(String value1, String value2) {
            addCriterion("TRANS_STATUS not between", value1, value2, "transStatus");
            return this;
        }

        public Criteria andTransIdIsNull() {
            addCriterion("TRANS_ID is null");
            return this;
        }

        public Criteria andTransIdIsNotNull() {
            addCriterion("TRANS_ID is not null");
            return this;
        }

        public Criteria andTransIdEqualTo(String value) {
            addCriterion("TRANS_ID =", value, "transId");
            return this;
        }

        public Criteria andTransIdNotEqualTo(String value) {
            addCriterion("TRANS_ID <>", value, "transId");
            return this;
        }

        public Criteria andTransIdGreaterThan(String value) {
            addCriterion("TRANS_ID >", value, "transId");
            return this;
        }

        public Criteria andTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_ID >=", value, "transId");
            return this;
        }

        public Criteria andTransIdLessThan(String value) {
            addCriterion("TRANS_ID <", value, "transId");
            return this;
        }

        public Criteria andTransIdLessThanOrEqualTo(String value) {
            addCriterion("TRANS_ID <=", value, "transId");
            return this;
        }

        public Criteria andTransIdLike(String value) {
            addCriterion("TRANS_ID like", value, "transId");
            return this;
        }

        public Criteria andTransIdNotLike(String value) {
            addCriterion("TRANS_ID not like", value, "transId");
            return this;
        }

        public Criteria andTransIdIn(List values) {
            addCriterion("TRANS_ID in", values, "transId");
            return this;
        }

        public Criteria andTransIdNotIn(List values) {
            addCriterion("TRANS_ID not in", values, "transId");
            return this;
        }

        public Criteria andTransIdBetween(String value1, String value2) {
            addCriterion("TRANS_ID between", value1, value2, "transId");
            return this;
        }

        public Criteria andTransIdNotBetween(String value1, String value2) {
            addCriterion("TRANS_ID not between", value1, value2, "transId");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}