package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "biz_agent_order", Class = BizAgentOrder.class)
public class BizAgentOrder<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.ORDER_NUM
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String orderNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.ORDER_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Date orderTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.STATUS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.RECEIVE_ADDRESS_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Long receiveAddressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.USER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.TOTAL_PRICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private BigDecimal totalPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.IS_INVOICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Integer isInvoice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_TYPE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Integer invoiceType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_HEAD
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceHead;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceCompanyName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_TAXPAYER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceTaxpayerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_ADDRESS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceAddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoicePhone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_BANK_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceBankName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.INVOICE_BANK_ACCOUNT
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String invoiceBankAccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.PAY_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Date payTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.PREPAY_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String prepayId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.QR_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Long qrFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.REMARK
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.EXTEND
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private String extend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column biz_agent_order.QR_PIC
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    @Column
    private byte[] qrPic;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.SN
     *
     * @return the value of biz_agent_order.SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.SN
     *
     * @param sn the value for biz_agent_order.SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.ORDER_NUM
     *
     * @return the value of biz_agent_order.ORDER_NUM
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.ORDER_NUM
     *
     * @param orderNum the value for biz_agent_order.ORDER_NUM
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.ORDER_TIME
     *
     * @return the value of biz_agent_order.ORDER_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.ORDER_TIME
     *
     * @param orderTime the value for biz_agent_order.ORDER_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.STATUS
     *
     * @return the value of biz_agent_order.STATUS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.STATUS
     *
     * @param status the value for biz_agent_order.STATUS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.RECEIVE_ADDRESS_ID
     *
     * @return the value of biz_agent_order.RECEIVE_ADDRESS_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getReceiveAddressId() {
        return receiveAddressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.RECEIVE_ADDRESS_ID
     *
     * @param receiveAddressId the value for biz_agent_order.RECEIVE_ADDRESS_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setReceiveAddressId(Long receiveAddressId) {
        this.receiveAddressId = receiveAddressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.USER_ID
     *
     * @return the value of biz_agent_order.USER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.USER_ID
     *
     * @param userId the value for biz_agent_order.USER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.TOTAL_PRICE
     *
     * @return the value of biz_agent_order.TOTAL_PRICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.TOTAL_PRICE
     *
     * @param totalPrice the value for biz_agent_order.TOTAL_PRICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.IS_INVOICE
     *
     * @return the value of biz_agent_order.IS_INVOICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Integer getIsInvoice() {
        return isInvoice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.IS_INVOICE
     *
     * @param isInvoice the value for biz_agent_order.IS_INVOICE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setIsInvoice(Integer isInvoice) {
        this.isInvoice = isInvoice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_TYPE
     *
     * @return the value of biz_agent_order.INVOICE_TYPE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_TYPE
     *
     * @param invoiceType the value for biz_agent_order.INVOICE_TYPE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_HEAD
     *
     * @return the value of biz_agent_order.INVOICE_HEAD
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceHead() {
        return invoiceHead;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_HEAD
     *
     * @param invoiceHead the value for biz_agent_order.INVOICE_HEAD
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceHead(String invoiceHead) {
        this.invoiceHead = invoiceHead;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_COMPANY_NAME
     *
     * @return the value of biz_agent_order.INVOICE_COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceCompanyName() {
        return invoiceCompanyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_COMPANY_NAME
     *
     * @param invoiceCompanyName the value for biz_agent_order.INVOICE_COMPANY_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceCompanyName(String invoiceCompanyName) {
        this.invoiceCompanyName = invoiceCompanyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_TAXPAYER_ID
     *
     * @return the value of biz_agent_order.INVOICE_TAXPAYER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceTaxpayerId() {
        return invoiceTaxpayerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_TAXPAYER_ID
     *
     * @param invoiceTaxpayerId the value for biz_agent_order.INVOICE_TAXPAYER_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceTaxpayerId(String invoiceTaxpayerId) {
        this.invoiceTaxpayerId = invoiceTaxpayerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_ADDRESS
     *
     * @return the value of biz_agent_order.INVOICE_ADDRESS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceAddress() {
        return invoiceAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_ADDRESS
     *
     * @param invoiceAddress the value for biz_agent_order.INVOICE_ADDRESS
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceAddress(String invoiceAddress) {
        this.invoiceAddress = invoiceAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_PHONE
     *
     * @return the value of biz_agent_order.INVOICE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoicePhone() {
        return invoicePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_PHONE
     *
     * @param invoicePhone the value for biz_agent_order.INVOICE_PHONE
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoicePhone(String invoicePhone) {
        this.invoicePhone = invoicePhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_BANK_NAME
     *
     * @return the value of biz_agent_order.INVOICE_BANK_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceBankName() {
        return invoiceBankName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_BANK_NAME
     *
     * @param invoiceBankName the value for biz_agent_order.INVOICE_BANK_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceBankName(String invoiceBankName) {
        this.invoiceBankName = invoiceBankName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.INVOICE_BANK_ACCOUNT
     *
     * @return the value of biz_agent_order.INVOICE_BANK_ACCOUNT
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getInvoiceBankAccount() {
        return invoiceBankAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.INVOICE_BANK_ACCOUNT
     *
     * @param invoiceBankAccount the value for biz_agent_order.INVOICE_BANK_ACCOUNT
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setInvoiceBankAccount(String invoiceBankAccount) {
        this.invoiceBankAccount = invoiceBankAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.PAY_TIME
     *
     * @return the value of biz_agent_order.PAY_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.PAY_TIME
     *
     * @param payTime the value for biz_agent_order.PAY_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.PREPAY_ID
     *
     * @return the value of biz_agent_order.PREPAY_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.PREPAY_ID
     *
     * @param prepayId the value for biz_agent_order.PREPAY_ID
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.QR_FILE_SN
     *
     * @return the value of biz_agent_order.QR_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getQrFileSn() {
        return qrFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.QR_FILE_SN
     *
     * @param qrFileSn the value for biz_agent_order.QR_FILE_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setQrFileSn(Long qrFileSn) {
        this.qrFileSn = qrFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.ADDER_SN
     *
     * @return the value of biz_agent_order.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.ADDER_SN
     *
     * @param adderSn the value for biz_agent_order.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.ADDER_NAME
     *
     * @return the value of biz_agent_order.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.ADDER_NAME
     *
     * @param adderName the value for biz_agent_order.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.ADD_TIME
     *
     * @return the value of biz_agent_order.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.ADD_TIME
     *
     * @param addTime the value for biz_agent_order.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.UPDATER_SN
     *
     * @return the value of biz_agent_order.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.UPDATER_SN
     *
     * @param updaterSn the value for biz_agent_order.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.UPDATER_NAME
     *
     * @return the value of biz_agent_order.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.UPDATER_NAME
     *
     * @param updaterName the value for biz_agent_order.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.UPDATE_TIME
     *
     * @return the value of biz_agent_order.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.UPDATE_TIME
     *
     * @param updateTime the value for biz_agent_order.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.REMARK
     *
     * @return the value of biz_agent_order.REMARK
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.REMARK
     *
     * @param remark the value for biz_agent_order.REMARK
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.EXTEND
     *
     * @return the value of biz_agent_order.EXTEND
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.EXTEND
     *
     * @param extend the value for biz_agent_order.EXTEND
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setExtend(String extend) {
        this.extend = extend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column biz_agent_order.QR_PIC
     *
     * @return the value of biz_agent_order.QR_PIC
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public byte[] getQrPic() {
        return qrPic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column biz_agent_order.QR_PIC
     *
     * @param qrPic the value for biz_agent_order.QR_PIC
     *
     * @ibatorgenerated Thu Aug 11 11:48:29 CST 2016
     */
    public void setQrPic(byte[] qrPic) {
        this.qrPic = qrPic;
    }
}