package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "biz_prod_case", Class = BizProdCase.class)
public class BizProdCaseCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public BizProdCaseCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public BizProdCaseCriteria(BizProdCaseCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public BizProdCaseCriteria(Object record, BizProdCaseCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table biz_prod_case
     *
     * @ibatorgenerated Mon May 16 17:58:01 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("TYPE in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("TYPE not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return this;
        }

        public Criteria andImageFileSnIsNull() {
            addCriterion("IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andImageFileSnIsNotNull() {
            addCriterion("IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andImageFileSnEqualTo(Long value) {
            addCriterion("IMAGE_FILE_SN =", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnNotEqualTo(Long value) {
            addCriterion("IMAGE_FILE_SN <>", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnGreaterThan(Long value) {
            addCriterion("IMAGE_FILE_SN >", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("IMAGE_FILE_SN >=", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnLessThan(Long value) {
            addCriterion("IMAGE_FILE_SN <", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("IMAGE_FILE_SN <=", value, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnIn(List values) {
            addCriterion("IMAGE_FILE_SN in", values, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnNotIn(List values) {
            addCriterion("IMAGE_FILE_SN not in", values, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnBetween(Long value1, Long value2) {
            addCriterion("IMAGE_FILE_SN between", value1, value2, "imageFileSn");
            return this;
        }

        public Criteria andImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("IMAGE_FILE_SN not between", value1, value2, "imageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnIsNull() {
            addCriterion("INDEX_IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andIndexImageFileSnIsNotNull() {
            addCriterion("INDEX_IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andIndexImageFileSnEqualTo(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN =", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnNotEqualTo(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN <>", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnGreaterThan(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN >", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN >=", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnLessThan(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN <", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("INDEX_IMAGE_FILE_SN <=", value, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnIn(List values) {
            addCriterion("INDEX_IMAGE_FILE_SN in", values, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnNotIn(List values) {
            addCriterion("INDEX_IMAGE_FILE_SN not in", values, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnBetween(Long value1, Long value2) {
            addCriterion("INDEX_IMAGE_FILE_SN between", value1, value2, "indexImageFileSn");
            return this;
        }

        public Criteria andIndexImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("INDEX_IMAGE_FILE_SN not between", value1, value2, "indexImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnIsNull() {
            addCriterion("SERVICE_IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andServiceImageFileSnIsNotNull() {
            addCriterion("SERVICE_IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andServiceImageFileSnEqualTo(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN =", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnNotEqualTo(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN <>", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnGreaterThan(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN >", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN >=", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnLessThan(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN <", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("SERVICE_IMAGE_FILE_SN <=", value, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnIn(List values) {
            addCriterion("SERVICE_IMAGE_FILE_SN in", values, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnNotIn(List values) {
            addCriterion("SERVICE_IMAGE_FILE_SN not in", values, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnBetween(Long value1, Long value2) {
            addCriterion("SERVICE_IMAGE_FILE_SN between", value1, value2, "serviceImageFileSn");
            return this;
        }

        public Criteria andServiceImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("SERVICE_IMAGE_FILE_SN not between", value1, value2, "serviceImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnIsNull() {
            addCriterion("CIEF_IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andCiefImageFileSnIsNotNull() {
            addCriterion("CIEF_IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andCiefImageFileSnEqualTo(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN =", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnNotEqualTo(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN <>", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnGreaterThan(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN >", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN >=", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnLessThan(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN <", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("CIEF_IMAGE_FILE_SN <=", value, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnIn(List values) {
            addCriterion("CIEF_IMAGE_FILE_SN in", values, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnNotIn(List values) {
            addCriterion("CIEF_IMAGE_FILE_SN not in", values, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnBetween(Long value1, Long value2) {
            addCriterion("CIEF_IMAGE_FILE_SN between", value1, value2, "ciefImageFileSn");
            return this;
        }

        public Criteria andCiefImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("CIEF_IMAGE_FILE_SN not between", value1, value2, "ciefImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnIsNull() {
            addCriterion("ABOUT_IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andAboutImageFileSnIsNotNull() {
            addCriterion("ABOUT_IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andAboutImageFileSnEqualTo(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN =", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnNotEqualTo(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN <>", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnGreaterThan(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN >", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN >=", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnLessThan(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN <", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("ABOUT_IMAGE_FILE_SN <=", value, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnIn(List values) {
            addCriterion("ABOUT_IMAGE_FILE_SN in", values, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnNotIn(List values) {
            addCriterion("ABOUT_IMAGE_FILE_SN not in", values, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnBetween(Long value1, Long value2) {
            addCriterion("ABOUT_IMAGE_FILE_SN between", value1, value2, "aboutImageFileSn");
            return this;
        }

        public Criteria andAboutImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("ABOUT_IMAGE_FILE_SN not between", value1, value2, "aboutImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnIsNull() {
            addCriterion("CASE_IMAGE_FILE_SN is null");
            return this;
        }

        public Criteria andCaseImageFileSnIsNotNull() {
            addCriterion("CASE_IMAGE_FILE_SN is not null");
            return this;
        }

        public Criteria andCaseImageFileSnEqualTo(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN =", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnNotEqualTo(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN <>", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnGreaterThan(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN >", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnGreaterThanOrEqualTo(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN >=", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnLessThan(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN <", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnLessThanOrEqualTo(Long value) {
            addCriterion("CASE_IMAGE_FILE_SN <=", value, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnIn(List values) {
            addCriterion("CASE_IMAGE_FILE_SN in", values, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnNotIn(List values) {
            addCriterion("CASE_IMAGE_FILE_SN not in", values, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnBetween(Long value1, Long value2) {
            addCriterion("CASE_IMAGE_FILE_SN between", value1, value2, "caseImageFileSn");
            return this;
        }

        public Criteria andCaseImageFileSnNotBetween(Long value1, Long value2) {
            addCriterion("CASE_IMAGE_FILE_SN not between", value1, value2, "caseImageFileSn");
            return this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameIn(List values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotIn(List values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return this;
        }

        public Criteria andMainProductIsNull() {
            addCriterion("MAIN_PRODUCT is null");
            return this;
        }

        public Criteria andMainProductIsNotNull() {
            addCriterion("MAIN_PRODUCT is not null");
            return this;
        }

        public Criteria andMainProductEqualTo(String value) {
            addCriterion("MAIN_PRODUCT =", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductNotEqualTo(String value) {
            addCriterion("MAIN_PRODUCT <>", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductGreaterThan(String value) {
            addCriterion("MAIN_PRODUCT >", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductGreaterThanOrEqualTo(String value) {
            addCriterion("MAIN_PRODUCT >=", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductLessThan(String value) {
            addCriterion("MAIN_PRODUCT <", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductLessThanOrEqualTo(String value) {
            addCriterion("MAIN_PRODUCT <=", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductLike(String value) {
            addCriterion("MAIN_PRODUCT like", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductNotLike(String value) {
            addCriterion("MAIN_PRODUCT not like", value, "mainProduct");
            return this;
        }

        public Criteria andMainProductIn(List values) {
            addCriterion("MAIN_PRODUCT in", values, "mainProduct");
            return this;
        }

        public Criteria andMainProductNotIn(List values) {
            addCriterion("MAIN_PRODUCT not in", values, "mainProduct");
            return this;
        }

        public Criteria andMainProductBetween(String value1, String value2) {
            addCriterion("MAIN_PRODUCT between", value1, value2, "mainProduct");
            return this;
        }

        public Criteria andMainProductNotBetween(String value1, String value2) {
            addCriterion("MAIN_PRODUCT not between", value1, value2, "mainProduct");
            return this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return this;
        }

        public Criteria andUrlIn(List values) {
            addCriterion("URL in", values, "url");
            return this;
        }

        public Criteria andUrlNotIn(List values) {
            addCriterion("URL not in", values, "url");
            return this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("PRIORITY =", value, "priority");
            return this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("PRIORITY <>", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("PRIORITY >", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY >=", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("PRIORITY <", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY <=", value, "priority");
            return this;
        }

        public Criteria andPriorityIn(List values) {
            addCriterion("PRIORITY in", values, "priority");
            return this;
        }

        public Criteria andPriorityNotIn(List values) {
            addCriterion("PRIORITY not in", values, "priority");
            return this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return this;
        }

        public Criteria andValidFlagIsNull() {
            addCriterion("VALID_FLAG is null");
            return this;
        }

        public Criteria andValidFlagIsNotNull() {
            addCriterion("VALID_FLAG is not null");
            return this;
        }

        public Criteria andValidFlagEqualTo(Integer value) {
            addCriterion("VALID_FLAG =", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagNotEqualTo(Integer value) {
            addCriterion("VALID_FLAG <>", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagGreaterThan(Integer value) {
            addCriterion("VALID_FLAG >", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALID_FLAG >=", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagLessThan(Integer value) {
            addCriterion("VALID_FLAG <", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagLessThanOrEqualTo(Integer value) {
            addCriterion("VALID_FLAG <=", value, "validFlag");
            return this;
        }

        public Criteria andValidFlagIn(List values) {
            addCriterion("VALID_FLAG in", values, "validFlag");
            return this;
        }

        public Criteria andValidFlagNotIn(List values) {
            addCriterion("VALID_FLAG not in", values, "validFlag");
            return this;
        }

        public Criteria andValidFlagBetween(Integer value1, Integer value2) {
            addCriterion("VALID_FLAG between", value1, value2, "validFlag");
            return this;
        }

        public Criteria andValidFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("VALID_FLAG not between", value1, value2, "validFlag");
            return this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("SUMMARY is null");
            return this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("SUMMARY is not null");
            return this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("SUMMARY =", value, "summary");
            return this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("SUMMARY <>", value, "summary");
            return this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("SUMMARY >", value, "summary");
            return this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("SUMMARY >=", value, "summary");
            return this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("SUMMARY <", value, "summary");
            return this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("SUMMARY <=", value, "summary");
            return this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("SUMMARY like", value, "summary");
            return this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("SUMMARY not like", value, "summary");
            return this;
        }

        public Criteria andSummaryIn(List values) {
            addCriterion("SUMMARY in", values, "summary");
            return this;
        }

        public Criteria andSummaryNotIn(List values) {
            addCriterion("SUMMARY not in", values, "summary");
            return this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("SUMMARY between", value1, value2, "summary");
            return this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("SUMMARY not between", value1, value2, "summary");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}