package com.focustech.focus3d.agent.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "fnt_house_upload", Class = FntHouseUpload.class)
public class FntHouseUpload<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private String houseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Long houseFileSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    @Column
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.SN
     *
     * @return the value of fnt_house_upload.SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.SN
     *
     * @param sn the value for fnt_house_upload.SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.HOUSE_NAME
     *
     * @return the value of fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.HOUSE_NAME
     *
     * @param houseName the value for fnt_house_upload.HOUSE_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @return the value of fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Long getHouseFileSn() {
        return houseFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.HOUSE_FILE_SN
     *
     * @param houseFileSn the value for fnt_house_upload.HOUSE_FILE_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setHouseFileSn(Long houseFileSn) {
        this.houseFileSn = houseFileSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.USER_ID
     *
     * @return the value of fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.USER_ID
     *
     * @param userId the value for fnt_house_upload.USER_ID
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADDER_SN
     *
     * @return the value of fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADDER_SN
     *
     * @param adderSn the value for fnt_house_upload.ADDER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADDER_NAME
     *
     * @return the value of fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADDER_NAME
     *
     * @param adderName the value for fnt_house_upload.ADDER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.ADD_TIME
     *
     * @return the value of fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.ADD_TIME
     *
     * @param addTime the value for fnt_house_upload.ADD_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATER_SN
     *
     * @return the value of fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATER_SN
     *
     * @param updaterSn the value for fnt_house_upload.UPDATER_SN
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATER_NAME
     *
     * @return the value of fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATER_NAME
     *
     * @param updaterName the value for fnt_house_upload.UPDATER_NAME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column fnt_house_upload.UPDATE_TIME
     *
     * @return the value of fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column fnt_house_upload.UPDATE_TIME
     *
     * @param updateTime the value for fnt_house_upload.UPDATE_TIME
     *
     * @ibatorgenerated Wed Oct 19 11:13:22 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}